<?php

/**
 *  @see hook_menu()
 */
function custom_admin_menu() {
    $items['admin/custom'] = array(
		'title' => t('Custom Configuration'),
		'description' => 'Custom configuration.',
		'access arguments' => array('administrator site configuration'),
        'page callback' => 'custom_configuration',
        'type' => MENU_NORMAL_ITEM,	
	);
    $items['admin/custom/social-link'] = array(
        'title' => 'Social Link',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('custom_admin_social_form'),
        'access arguments' => array('administrator site configuration'),		
        'type' => MENU_NORMAL_ITEM,		
    );
    return $items;
}

/**
 * Implements hook_permission().
 */
function custom_admin_permission() {
    return array(
        'access simple page' => array(
            'title' => t('Access simple page'),
            'description' => t('Allow users to access simple page'),
        ),
    );
}

/**
 * Custom configuration
 */
function custom_configuration() {
	$out = 'Custom configuration';
	return $out;
}
/**
 * Social Form
 */
function custom_admin_social_form($form, &$form_state){
    $form = array();
    $form['social_facebook_link'] = array(
        '#type' => 'textfield', 
        '#title' => t('Facebook'), 
        '#size' => 60, 
        '#maxlength' => 255, 
        '#required' => TRUE,
        '#default_value' =>  variable_get('social_facebook_link', '#'),
    );
    $form['social_google_link'] = array(
        '#type' => 'textfield', 
        '#title' => t('Google'), 
        '#size' => 60, 
        '#maxlength' => 255, 
        '#required' => TRUE,
        '#default_value' =>  variable_get('social_google_link', '#'),
    );
    return system_settings_form($form);
}

function custom_admin_views_query_alter(&$view, &$query) {
    if($view->name  === 'violation_error' && $view->current_display == 'violation_error_page'){
        if(arg(0) == 'loi-vi-pham'){
            switch (arg(1)) {
                case 'xe-moto':
                    $query->where[0]['conditions'][0]['value'] = 0;
                    break;
                case 'xe-oto':
                    $query->where[0]['conditions'][0]['value'] = 1;
                    break;
                case 'xe-khach':
                    $query->where[0]['conditions'][0]['value'] = 2;
                    break;
                case 'xe-tai':
                    $query->where[0]['conditions'][0]['value'] = 3;
                    break;
                case 'nguoi-di-bo':
                    $query->where[0]['conditions'][0]['value'] = 4;
                    break;
                case 'nguoi-tham-gia-giao-thong':
                    $query->where[0]['conditions'][0]['value'] = 5;
                    break;

                default:
                    drupal_not_found();
                    module_invoke_all('exit');
                    drupal_exit();
                    break;
            }
        }
    }
}